/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 --transform .\KeyLock.glb 
Files: .\KeyLock.glb [29.89MB] > C:\pedro\kodigo-solutions\public\models\KeyLock-transformed.glb [939.99KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/KeyLock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Extrude_2.geometry} material={materials.silver} position={[-0.074, 0.075, -2.222]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cube_1_9.geometry} material={materials.PaletteMaterial001} position={[3.215, 2.178, -10.211]} scale={0.01} />
      <mesh geometry={nodes.Cube_5_10.geometry} material={materials.PaletteMaterial002} position={[3.077, 2.178, -10.007]} scale={0.01} />
      <mesh geometry={nodes.Path_1_2.geometry} material={materials.gold} position={[2.326, 2.192, -7.144]} rotation={[-Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cube_8_4.geometry} material={nodes.Cube_8_4.material} position={[2.402, 4.055, -2.828]} rotation={[Math.PI / 2, -0.262, 0]} scale={0.01} />
      <instancedMesh args={[nodes.Mesh107.geometry, materials.PaletteMaterial001, 10]} instanceMatrix={nodes.Mesh107.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh106.geometry, materials.PaletteMaterial001, 10]} instanceMatrix={nodes.Mesh106.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh085.geometry, materials.PaletteMaterial001, 9]} instanceMatrix={nodes.Mesh085.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh084.geometry, materials.PaletteMaterial001, 9]} instanceMatrix={nodes.Mesh084.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh071.geometry, materials.silver, 24]} instanceMatrix={nodes.Mesh071.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh185.geometry, nodes.Mesh185.material, 5]} instanceMatrix={nodes.Mesh185.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh192.geometry, nodes.Mesh192.material, 5]} instanceMatrix={nodes.Mesh192.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh083.geometry, materials.PaletteMaterial002, 9]} instanceMatrix={nodes.Mesh083.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh083_1.geometry, materials.PaletteMaterial001, 9]} instanceMatrix={nodes.Mesh083_1.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/KeyLock-transformed.glb')
