/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 --transform .\Llave.glb 
Files: .\Llave.glb [534.79KB] > C:\pedro\kodigo-solutions\public\models\models/key.glb [26.28KB] (95%)
*/
import React from 'react';

import { useGLTF } from '@react-three/drei';

export function Key(props) {
  const { nodes, materials } = useGLTF('/models/key.glb');
  return (
    <group {...props} dispose={null} rotation={[Math.PI / 2, 0, 0]}>
      <mesh
        geometry={nodes['ref-logo'].geometry}
        material={materials.PaletteMaterial004}
        position={[0.278, 0.087, -4.621]}
        rotation={[0, -1.555, 0]}
        scale={0.01}
      >
        <meshStandardMaterial
          color="#F1C65F" // El color dorado en hexadecimal (parecido al oro)
          metalness={1} // Alto valor de metalness para apariencia metálica
          roughness={0.2} // Baja rugosidad para reflejos brillantes
        />
      </mesh>
      <mesh
        geometry={nodes.Llave.geometry}
        material={materials.PaletteMaterial003}
      >
        <meshStandardMaterial
          color="#C0C0C0" // Color plateado en hexadecimal
          metalness={1} // Alto valor de metalness para apariencia metálica
          roughness={0.08} // Muy baja rugosidad para reflejos brillantes
          side={2}
        />
      </mesh>
      <group position={[0.656, -0.28, 4.763]} scale={0.01}>
        <mesh
          geometry={nodes['line-1-bw_1'].geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes['line-1-bw_2'].geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <instancedMesh
        args={[nodes['ref-pin-a-1'].geometry, materials.PaletteMaterial003, 12]}
        instanceMatrix={nodes['ref-pin-a-1'].instanceMatrix}
      >
        <meshStandardMaterial
          color="#C0C0C0" // Color plateado en hexadecimal
          metalness={1} // Alto valor de metalness para apariencia metálica
          roughness={0.01} // Muy baja rugosidad para reflejos brillantes
        />
      </instancedMesh>
    </group>
  );
}

useGLTF.preload('/models/key.glb');
